name: kdv
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_app_name:
  name: "KDV Hesap Makinesi"

flutter_icons:
  android: "logoicon"
  ios: true
  image_path: "assets/icon.png"
# flutter pub run change_app_package_name:main com.kdv.com
# flutter pub run flutter_launcher_icons:main
# flutter pub run flutter_app_name

# flutter build appbundle

# dart fix --dry-run
# dart fix --apply
# flutter format .
# dart migrate.


# flutter clean
# flutter pub get
# cd ios
# pod deintegrate
# pod install